# Generated by Django 3.1.3 on 2021-01-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
